# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de Complemento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de edici\xf3n')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Complemento',
                'verbose_name_plural': 'Complementos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='services', verbose_name='Imagen')),
                ('created', models.TimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated', models.TimeField(auto_now=True, verbose_name='Fecha de edici\xf3n')),
                ('features', models.ManyToManyField(to='services.Features')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de Sub Servicio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaci\xf3n')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edici\xf3n')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'subServicio',
                'verbose_name_plural': 'subServicios',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='subService',
            field=models.ManyToManyField(to='services.SubService'),
        ),
    ]
