# Generated by Django 2.2.3 on 2019-10-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('S', 'Plata'), ('G', 'Oro'), ('P', 'Platino')], default='S', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomArticulo', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(max_length=9)),
                ('CategoriaArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.CategoriaArticulo')),
            ],
        ),
    ]
